# Generated by Django 4.2.3 on 2023-07-05 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000000000)),
                ('Date_Posted', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 5, 12, 41, 35, 105175))),
            ],
        ),
    ]
